version: '3.1'
services:
  web:
    build: .
    ports:
     - "8080:8080"
    env_file: .env
    depends_on:
      - "db"
    # command: ["./wait-for-postgres.sh", "db", "go-askme"]
    command: ["./wait-for-it.sh", "db:5432", "--", "go-askme"]
  adminer:
    image: "adminer:latest"
    restart: always
    depends_on:
      - "db"
    ports:
      - 8081:8080  
  db:
    image: "postgres:latest"
    restart: always
    ports:
     - "5432:5432"
    env_file: .env