FROM golang:1.8

WORKDIR /go/src/github.com/bashmohandes/go-askme
COPY . .
ENV GOBIN="$GOPATH/bin"
RUN go get -d -v ./...
RUN go get -u github.com/gobuffalo/packr/... && packr install -v ./cmd/askme/main.go
CMD ["main"]